# Generated by Django 6.1 on 2026-08-07 18:06

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgriShop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('shop_type', models.CharField(choices=[('SHOP', 'Agriculture Store'), ('HOSPITAL', 'Plant Hospital / Diagnostic Lab'), ('WAREHOUSE', 'Warehouse & Storage'), ('COLD_STORAGE', 'Cold Storage Unit'), ('MARKET', 'Mandi / Agri Market')], default='SHOP', max_length=30)),
                ('address', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=30)),
                ('latitude', models.FloatField(default=12.9716)),
                ('longitude', models.FloatField(default=77.5946)),
                ('products_available', models.TextField(default='Seeds, Bio-Pesticides, Organic Fertilizers, Micro-nutrients')),
                ('rating', models.FloatField(default=4.7)),
            ],
        ),
        migrations.CreateModel(
            name='Crop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('scientific_name', models.CharField(blank=True, max_length=150, null=True)),
                ('category', models.CharField(default='Grain', max_length=50)),
                ('optimal_n', models.IntegerField(default=120)),
                ('optimal_p', models.IntegerField(default=60)),
                ('optimal_k', models.IntegerField(default=40)),
                ('optimal_ph_min', models.FloatField(default=6.0)),
                ('optimal_ph_max', models.FloatField(default=7.5)),
                ('water_req_mm', models.IntegerField(default=500)),
                ('growth_days', models.IntegerField(default=120)),
                ('icon_emoji', models.CharField(default='🌾', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='GovernmentScheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('category', models.CharField(default='Financial Subsidy', max_length=100)),
                ('eligibility', models.TextField()),
                ('required_documents', models.TextField()),
                ('deadline', models.DateField(blank=True, null=True)),
                ('apply_url', models.URLField()),
                ('funding_amount', models.CharField(default='Up to ₹50,000 / acre', max_length=100)),
                ('state', models.CharField(default='All India', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='WeatherRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_name', models.CharField(default='Bengaluru', max_length=100)),
                ('temp_c', models.FloatField(default=28.5)),
                ('humidity', models.IntegerField(default=65)),
                ('rainfall_mm', models.FloatField(default=12.0)),
                ('wind_kph', models.FloatField(default=14.0)),
                ('uv_index', models.IntegerField(default=6)),
                ('alert_level', models.CharField(default='NORMAL', max_length=20)),
                ('alert_title', models.CharField(blank=True, max_length=150, null=True)),
                ('alert_desc', models.TextField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('FARMER', 'Farmer'), ('EXPERT', 'Agriculture Expert'), ('ADMIN', 'Platform Admin'), ('GOVT_OFFICER', 'Government Officer'), ('SHOP_OWNER', 'Agriculture Shop Owner')], default='FARMER', max_length=20)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('preferred_language', models.CharField(default='en', max_length=10)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('is_phone_verified', models.BooleanField(default=False)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profiles/')),
                ('green_points', models.IntegerField(default=100)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=255)),
                ('details', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Disease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('scientific_name', models.CharField(blank=True, max_length=150, null=True)),
                ('severity_default', models.CharField(default='Medium', max_length=20)),
                ('symptoms', models.TextField()),
                ('causes', models.TextField()),
                ('organic_treatment', models.TextField()),
                ('chemical_treatment', models.TextField()),
                ('required_pesticide', models.CharField(blank=True, max_length=255, null=True)),
                ('required_fertilizer', models.CharField(blank=True, max_length=255, null=True)),
                ('recovery_days', models.IntegerField(default=14)),
                ('prevention_tips', models.TextField()),
                ('crop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diseases', to='api.crop')),
            ],
        ),
        migrations.CreateModel(
            name='ExpertProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialization', models.CharField(default='Crop Pathology & Soil Chemistry', max_length=150)),
                ('qualification', models.CharField(default='Ph.D. Agronomy (UAS Bangalore)', max_length=150)),
                ('experience_years', models.IntegerField(default=12)),
                ('rating', models.FloatField(default=4.9)),
                ('consultation_fee', models.FloatField(default=0.0)),
                ('bio', models.TextField(default='Senior Plant Pathologist specializing in rice, wheat, and commercial horticulture diseases.')),
                ('is_available', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='expert_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('CONFIRMED', 'Confirmed'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('meeting_url', models.URLField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='farmer_appointments', to=settings.AUTH_USER_MODEL)),
                ('expert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expert_appointments', to='api.expertprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Farm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('area_acres', models.FloatField(default=1.0)),
                ('soil_type', models.CharField(default='Loamy', max_length=50)),
                ('village', models.CharField(blank=True, max_length=100, null=True)),
                ('state', models.CharField(default='Karnataka', max_length=100)),
                ('latitude', models.FloatField(default=12.9716)),
                ('longitude', models.FloatField(default=77.5946)),
                ('qr_code_id', models.CharField(default=uuid.uuid4, max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='farms', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DiseaseReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detected_disease_name', models.CharField(max_length=150)),
                ('confidence_score', models.FloatField(default=95.0)),
                ('severity', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], default='MEDIUM', max_length=20)),
                ('affected_area_pct', models.FloatField(default=15.0)),
                ('image', models.ImageField(blank=True, null=True, upload_to='disease_scans/')),
                ('image_url_override', models.URLField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('crop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.crop')),
                ('disease', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.disease')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disease_reports', to=settings.AUTH_USER_MODEL)),
                ('farm', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.farm')),
            ],
        ),
        migrations.CreateModel(
            name='FarmRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_type', models.CharField(choices=[('INCOME', 'Income / Crop Sale'), ('EXPENSE', 'Expense'), ('HARVEST', 'Harvest Yield'), ('SEEDS', 'Seeds Purchased'), ('FERTILIZER', 'Fertilizer Applied'), ('PESTICIDE', 'Pesticide Sprayed'), ('EQUIPMENT', 'Equipment Rental'), ('WORKERS', 'Labor Wages')], default='EXPENSE', max_length=20)),
                ('title', models.CharField(max_length=150)),
                ('amount', models.FloatField()),
                ('quantity_kg', models.FloatField(default=0.0)),
                ('date', models.DateField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='api.farm')),
            ],
        ),
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('area_acres', models.FloatField(default=1.0)),
                ('planted_date', models.DateField(blank=True, null=True)),
                ('crop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.crop')),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='api.farm')),
            ],
        ),
        migrations.CreateModel(
            name='MarketPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('market_name', models.CharField(max_length=100)),
                ('state', models.CharField(default='Karnataka', max_length=100)),
                ('price_per_quintal', models.FloatField()),
                ('prev_price', models.FloatField(default=0.0)),
                ('price_change_pct', models.FloatField(default=0.0)),
                ('demand_level', models.CharField(default='HIGH', max_length=20)),
                ('best_sell_day', models.CharField(default='Thursday', max_length=50)),
                ('date', models.DateField(auto_now_add=True)),
                ('crop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='market_prices', to='api.crop')),
            ],
        ),
        migrations.CreateModel(
            name='SoilHealthRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nitrogen', models.FloatField(default=110)),
                ('phosphorus', models.FloatField(default=45)),
                ('potassium', models.FloatField(default=35)),
                ('ph', models.FloatField(default=6.8)),
                ('organic_carbon', models.FloatField(default=0.65)),
                ('moisture_pct', models.FloatField(default=40.0)),
                ('health_score', models.IntegerField(default=88)),
                ('recommendation_summary', models.TextField(default='Soil NPK balance is optimal. Recommended minor organic nitrogen boost.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='soil_records', to='api.farm')),
            ],
        ),
        migrations.CreateModel(
            name='SchemeBookmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('scheme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.governmentscheme')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheme_bookmarks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'scheme')},
            },
        ),
    ]
