# Generated by Django 6.1 on 2026-08-07 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_diseasereport_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='crop',
            name='major_producing_states',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='crop',
            name='category',
            field=models.CharField(default='Cereals', max_length=50),
        ),
    ]
