# Generated by Django 6.1 on 2026-08-07 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_crop_major_producing_states_alter_crop_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='crop',
            name='main_uses',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='crop',
            name='season',
            field=models.CharField(default='Kharif', max_length=50),
        ),
        migrations.AddField(
            model_name='crop',
            name='soil_and_climate',
            field=models.TextField(blank=True, null=True),
        ),
    ]
