# Generated by Django 6.1 on 2026-08-07 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_crop_main_uses_crop_season_crop_soil_and_climate'),
    ]

    operations = [
        migrations.CreateModel(
            name='SoilRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_name', models.CharField(default='Bengaluru', max_length=100)),
                ('latitude', models.FloatField(default=12.9716)),
                ('longitude', models.FloatField(default=77.5946)),
                ('soil_type', models.CharField(default='Red Sandy Loam', max_length=100)),
                ('ph_level', models.FloatField(default=6.5)),
                ('organic_carbon_pct', models.FloatField(default=0.65)),
                ('nitrogen_level', models.CharField(default='Medium', max_length=50)),
                ('phosphorus_level', models.CharField(default='Medium', max_length=50)),
                ('potassium_level', models.CharField(default='High', max_length=50)),
                ('drainage_quality', models.CharField(default='Moderate', max_length=50)),
                ('common_soil_diseases', models.TextField(default='Root Rot, Fusarium Wilt, Nematode Infection')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='diseasereport',
            name='soil_pathogen_risk',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='diseasereport',
            name='soil_ph',
            field=models.FloatField(blank=True, default=6.5, null=True),
        ),
        migrations.AddField(
            model_name='diseasereport',
            name='soil_type',
            field=models.CharField(blank=True, default='Red Sandy Loam', max_length=100, null=True),
        ),
    ]
